version: "3.9"

services:
  base_datos:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodstore_new
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  servidor:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - base_datos
    env_file: .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@base_datos:5432/foodstore_new

volumes:
  pgdata:
